<?php

namespace Database\Seeders;

use App\Models\Subcategory;
use App\Models\Subdistrict;
use Illuminate\Database\Seeder;
class SubDistricts extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Subdistrict::insert([
            ['id' => 1, 'district_id' => 1, 'subdistrict_tr' => 'ALADAĞ'],
            ['id' => 2, 'district_id' => 1, 'subdistrict_tr' => 'CEYHAN'],
            ['id' => 3, 'district_id' => 1, 'subdistrict_tr' => 'ÇUKUROVA'],
            ['id' => 4, 'district_id' => 1, 'subdistrict_tr' => 'FEKE'],
            ['id' => 5, 'district_id' => 1, 'subdistrict_tr' => 'İMAMOĞLU'],
            ['id' => 6, 'district_id' => 1, 'subdistrict_tr' => 'KARAİSALI'],
            ['id' => 7, 'district_id' => 1, 'subdistrict_tr' => 'KARATAŞ'],
            ['id' => 8, 'district_id' => 1, 'subdistrict_tr' => 'KOZAN'],
            ['id' => 9, 'district_id' => 1, 'subdistrict_tr' => 'POZANTI'],
            ['id' => 10, 'district_id' => 1, 'subdistrict_tr' => 'SAİMBEYLİ'],
            ['id' => 11, 'district_id' => 1, 'subdistrict_tr' => 'SARIÇAM'],
            ['id' => 12, 'district_id' => 1, 'subdistrict_tr' => 'SEYHAN'],
            ['id' => 13, 'district_id' => 1, 'subdistrict_tr' => 'TUFANBEYLİ'],
            ['id' => 14, 'district_id' => 1, 'subdistrict_tr' => 'YUMURTALIK'],
            ['id' => 15, 'district_id' => 1, 'subdistrict_tr' => 'YÜREĞİR'],
            ['id' => 16, 'district_id' => 2, 'subdistrict_tr' => 'BESNİ'],
            ['id' => 17, 'district_id' => 2, 'subdistrict_tr' => 'ÇELİKHAN'],
            ['id' => 18, 'district_id' => 2, 'subdistrict_tr' => 'GERGER'],
            ['id' => 19, 'district_id' => 2, 'subdistrict_tr' => 'GÖLBAŞI'],
            ['id' => 20, 'district_id' => 2, 'subdistrict_tr' => 'KAHTA'],
            ['id' => 21, 'district_id' => 2, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 22, 'district_id' => 2, 'subdistrict_tr' => 'SAMSAT'],
            ['id' => 23, 'district_id' => 2, 'subdistrict_tr' => 'SİNCİK'],
            ['id' => 24, 'district_id' => 2, 'subdistrict_tr' => 'TUT'],
            ['id' => 25, 'district_id' => 3, 'subdistrict_tr' => 'BAŞMAKÇI'],
            ['id' => 26, 'district_id' => 3, 'subdistrict_tr' => 'BAYAT'],
            ['id' => 27, 'district_id' => 3, 'subdistrict_tr' => 'BOLVADİN'],
            ['id' => 28, 'district_id' => 3, 'subdistrict_tr' => 'ÇAY'],
            ['id' => 29, 'district_id' => 3, 'subdistrict_tr' => 'ÇOBANLAR'],
            ['id' => 30, 'district_id' => 3, 'subdistrict_tr' => 'DAZKIRI'],
            ['id' => 31, 'district_id' => 3, 'subdistrict_tr' => 'DİNAR'],
            ['id' => 32, 'district_id' => 3, 'subdistrict_tr' => 'EMİRDAĞ'],
            ['id' => 33, 'district_id' => 3, 'subdistrict_tr' => 'EVCİLER'],
            ['id' => 34, 'district_id' => 3, 'subdistrict_tr' => 'HOCALAR'],
            ['id' => 35, 'district_id' => 3, 'subdistrict_tr' => 'İHSANİYE'],
            ['id' => 36, 'district_id' => 3, 'subdistrict_tr' => 'İSCEHİSAR'],
            ['id' => 37, 'district_id' => 3, 'subdistrict_tr' => 'KIZILÖREN'],
            ['id' => 38, 'district_id' => 3, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 39, 'district_id' => 3, 'subdistrict_tr' => 'SANDIKLI'],
            ['id' => 40, 'district_id' => 3, 'subdistrict_tr' => 'SİNANPAŞA'],
            ['id' => 41, 'district_id' => 3, 'subdistrict_tr' => 'SULTANDAĞI'],
            ['id' => 42, 'district_id' => 3, 'subdistrict_tr' => 'ŞUHUT'],
            //Ağrı
            ['id' => 43, 'district_id' => 4, 'subdistrict_tr' => 'DİYADİN'],
            ['id' => 44, 'district_id' => 4, 'subdistrict_tr' => 'DOĞUBAYAZIT'],
            ['id' => 45, 'district_id' => 4, 'subdistrict_tr' => 'ELEŞKİRT'],
            ['id' => 46, 'district_id' => 4, 'subdistrict_tr' => 'HAMUR'],
            ['id' => 47, 'district_id' => 4, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 48, 'district_id' => 4, 'subdistrict_tr' => 'PATNOS'],
            ['id' => 49, 'district_id' => 4, 'subdistrict_tr' => 'TAŞLIÇAY'],
            ['id' => 50, 'district_id' => 4, 'subdistrict_tr' => 'TUTAK'],
            //AKSARAY
            ['id' => 51, 'district_id' => 68, 'subdistrict_tr' => 'AĞAÇÖREN'],
            ['id' => 52, 'district_id' => 68, 'subdistrict_tr' => 'ESKİL'],
            ['id' => 53, 'district_id' => 68, 'subdistrict_tr' => 'GÜLAĞAÇ'],
            ['id' => 54, 'district_id' => 68, 'subdistrict_tr' => 'GÜZELYURT'],
            ['id' => 55, 'district_id' => 68, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 56, 'district_id' => 68, 'subdistrict_tr' => 'ORTAKÖY'],
            ['id' => 57, 'district_id' => 68, 'subdistrict_tr' => 'SARIYAHŞİ'],
            ['id' => 58, 'district_id' => 68, 'subdistrict_tr' => 'SULTANHANI'],
            //AMASYA
            ['id' => 59, 'district_id' => 5, 'subdistrict_tr' => 'GÖYNÜCEK'],
            ['id' => 60, 'district_id' => 5, 'subdistrict_tr' => 'GÜMÜŞHACIKÖY'],
            ['id' => 61, 'district_id' => 5, 'subdistrict_tr' => 'HAMAMÖZÜ'],
            ['id' => 62, 'district_id' => 5, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 63, 'district_id' => 5, 'subdistrict_tr' => 'MERZİFON'],
            ['id' => 64, 'district_id' => 5, 'subdistrict_tr' => 'SULUOVA'],
            ['id' => 65, 'district_id' => 5, 'subdistrict_tr' => 'TAŞOVA'],
            //ANKARA
            ['id' => 66, 'district_id' => 6, 'subdistrict_tr' => 'AKYURT'],
            ['id' => 67, 'district_id' => 6, 'subdistrict_tr' => 'ALTINDAĞ'],
            ['id' => 68, 'district_id' => 6, 'subdistrict_tr' => 'AYAŞ'],
            ['id' => 69, 'district_id' => 6, 'subdistrict_tr' => 'BALA'],
            ['id' => 70, 'district_id' => 6, 'subdistrict_tr' => 'BEYPAZARI'],
            ['id' => 71, 'district_id' => 6, 'subdistrict_tr' => 'ÇAMLIDERE'],
            ['id' => 72, 'district_id' => 6, 'subdistrict_tr' => 'ÇANKAYA'],
            ['id' => 73, 'district_id' => 6, 'subdistrict_tr' => 'ÇUBUK'],
            ['id' => 74, 'district_id' => 6, 'subdistrict_tr' => 'ELMADAĞ'],
            ['id' => 75, 'district_id' => 6, 'subdistrict_tr' => 'ETİMESGUT'],
            ['id' => 76, 'district_id' => 6, 'subdistrict_tr' => 'EVREN'],
            ['id' => 77, 'district_id' => 6, 'subdistrict_tr' => 'GÖLBAŞI'],
            ['id' => 78, 'district_id' => 6, 'subdistrict_tr' => 'GÜDÜL'],
            ['id' => 79, 'district_id' => 6, 'subdistrict_tr' => 'HAYMANA'],
            ['id' => 80, 'district_id' => 6, 'subdistrict_tr' => 'KAHRAMANKAZAN'],
            ['id' => 81, 'district_id' => 6, 'subdistrict_tr' => 'KALECİK'],
            ['id' => 82, 'district_id' => 6, 'subdistrict_tr' => 'KEÇİÖREN'],
            ['id' => 83, 'district_id' => 6, 'subdistrict_tr' => 'KIZILCAHAMAM'],
            ['id' => 84, 'district_id' => 6, 'subdistrict_tr' => 'MAMAK'],
            ['id' => 85, 'district_id' => 6, 'subdistrict_tr' => 'NALLIHAN'],
            ['id' => 86, 'district_id' => 6, 'subdistrict_tr' => 'POLATLI'],
            ['id' => 87, 'district_id' => 6, 'subdistrict_tr' => 'PURSAKLAR'],
            ['id' => 88, 'district_id' => 6, 'subdistrict_tr' => 'SİNCAN'],
            ['id' => 89, 'district_id' => 6, 'subdistrict_tr' => 'ŞEREFLİKOÇHİSAR'],
            ['id' => 90, 'district_id' => 6, 'subdistrict_tr' => 'YENİMAHALLE'],
            //ANTALYA
            ['id' => 91, 'district_id' => 7, 'subdistrict_tr' => 'AKSEKİ'],
            ['id' => 92, 'district_id' => 7, 'subdistrict_tr' => 'AKSU'],
            ['id' => 93, 'district_id' => 7, 'subdistrict_tr' => 'ALANYA'],
            ['id' => 94, 'district_id' => 7, 'subdistrict_tr' => 'DEMRE'],
            ['id' => 95, 'district_id' => 7, 'subdistrict_tr' => 'DÖŞEMEALTI'],
            ['id' => 96, 'district_id' => 7, 'subdistrict_tr' => 'ELMALI'],
            ['id' => 97, 'district_id' => 7, 'subdistrict_tr' => 'FİNİKE'],
            ['id' => 98, 'district_id' => 7, 'subdistrict_tr' => 'GAZİPAŞA'],
            ['id' => 99, 'district_id' => 7, 'subdistrict_tr' => 'GÜNDOĞMUŞ'],
            ['id' => 100, 'district_id' => 7, 'subdistrict_tr' => 'İBRADI'],
            ['id' => 101, 'district_id' => 7, 'subdistrict_tr' => 'KAŞ'],
            ['id' => 102, 'district_id' => 7, 'subdistrict_tr' => 'KEMER'],
            ['id' => 103, 'district_id' => 7, 'subdistrict_tr' => 'KEPEZ'],
            ['id' => 104, 'district_id' => 7, 'subdistrict_tr' => 'KONYAALTI'],
            ['id' => 105, 'district_id' => 7, 'subdistrict_tr' => 'KORKUTELİ'],
            ['id' => 106, 'district_id' => 7, 'subdistrict_tr' => 'KUMLUCA'],
            ['id' => 107, 'district_id' => 7, 'subdistrict_tr' => 'MANAVGAT'],
            ['id' => 108, 'district_id' => 7, 'subdistrict_tr' => 'MURATPAŞA'],
            ['id' => 109, 'district_id' => 7, 'subdistrict_tr' => 'SERİK'],
            //ARDAHAN
            ['id' => 110, 'district_id' => 75, 'subdistrict_tr' => 'ÇILDIR'],
            ['id' => 111, 'district_id' => 75, 'subdistrict_tr' => 'DAMAL'],
            ['id' => 112, 'district_id' => 75, 'subdistrict_tr' => 'GÖLE'],
            ['id' => 113, 'district_id' => 75, 'subdistrict_tr' => 'HANAK'],
            ['id' => 114, 'district_id' => 75, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 115, 'district_id' => 75, 'subdistrict_tr' => 'POSOF'],
            //ARTVİN
            ['id' => 116, 'district_id' => 8, 'subdistrict_tr' => 'ARDANUÇ'],
            ['id' => 117, 'district_id' => 8, 'subdistrict_tr' => 'ARHAVİ'],
            ['id' => 118, 'district_id' => 8, 'subdistrict_tr' => 'BORÇKA'],
            ['id' => 119, 'district_id' => 8, 'subdistrict_tr' => 'HOPA'],
            ['id' => 120, 'district_id' => 8, 'subdistrict_tr' => 'KEMALPAŞA'],
            ['id' => 121, 'district_id' => 8, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 122, 'district_id' => 8, 'subdistrict_tr' => 'MURGUL'],
            ['id' => 123, 'district_id' => 8, 'subdistrict_tr' => 'ŞAVŞAT'],
            ['id' => 124, 'district_id' => 8, 'subdistrict_tr' => 'YUSUFELİ'],
            //AYDIN
            ['id' => 125, 'district_id' => 9, 'subdistrict_tr' => 'BOZDOĞAN'],
            ['id' => 126, 'district_id' => 9, 'subdistrict_tr' => 'BUHARKENT'],
            ['id' => 127, 'district_id' => 9, 'subdistrict_tr' => 'ÇİNE'],
            ['id' => 128, 'district_id' => 9, 'subdistrict_tr' => 'DİDİM'],
            ['id' => 129, 'district_id' => 9, 'subdistrict_tr' => 'EFELER'],
            ['id' => 130, 'district_id' => 9, 'subdistrict_tr' => 'GERMENCİK'],
            ['id' => 131, 'district_id' => 9, 'subdistrict_tr' => 'İNCİRLİOVA'],
            ['id' => 132, 'district_id' => 9, 'subdistrict_tr' => 'KARACASU'],
            ['id' => 133, 'district_id' => 9, 'subdistrict_tr' => 'KARPUZLU'],
            ['id' => 134, 'district_id' => 9, 'subdistrict_tr' => 'KOÇARLI'],
            ['id' => 135, 'district_id' => 9, 'subdistrict_tr' => 'KÖŞK'],
            ['id' => 136, 'district_id' => 9, 'subdistrict_tr' => 'KUŞADASI'],
            ['id' => 137, 'district_id' => 9, 'subdistrict_tr' => 'KUYUCAK'],
            ['id' => 138, 'district_id' => 9, 'subdistrict_tr' => 'NAZİLLİ'],
            ['id' => 139, 'district_id' => 9, 'subdistrict_tr' => 'SÖKE'],
            ['id' => 140, 'district_id' => 9, 'subdistrict_tr' => 'SULTANHİSAR'],
            ['id' => 141, 'district_id' => 9, 'subdistrict_tr' => 'YENİPAZAR'],
            //Balıkesir
            ['id' => 142, 'district_id' => 10, 'subdistrict_tr' => 'ALTIEYLÜL'],
            ['id' => 143, 'district_id' => 10, 'subdistrict_tr' => 'AYVALIK'],
            ['id' => 144, 'district_id' => 10, 'subdistrict_tr' => 'BALYA'],
            ['id' => 145, 'district_id' => 10, 'subdistrict_tr' => 'BANDIRMA'],
            ['id' => 146, 'district_id' => 10, 'subdistrict_tr' => 'BİGADİÇ'],
            ['id' => 147, 'district_id' => 10, 'subdistrict_tr' => 'BURHANİYE'],
            ['id' => 148, 'district_id' => 10, 'subdistrict_tr' => 'DURSUNBEY'],
            ['id' => 149, 'district_id' => 10, 'subdistrict_tr' => 'EDREMİT'],
            ['id' => 150, 'district_id' => 10, 'subdistrict_tr' => 'ERDEK'],
            ['id' => 151, 'district_id' => 10, 'subdistrict_tr' => 'GÖMEÇ'],
            ['id' => 152, 'district_id' => 10, 'subdistrict_tr' => 'GÖNEN'],
            ['id' => 153, 'district_id' => 10, 'subdistrict_tr' => 'HAVRAN'],
            ['id' => 154, 'district_id' => 10, 'subdistrict_tr' => 'İVRİNDİ'],
            ['id' => 155, 'district_id' => 10, 'subdistrict_tr' => 'KARESİ'],
            ['id' => 156, 'district_id' => 10, 'subdistrict_tr' => 'KEPSUT'],
            ['id' => 157, 'district_id' => 10, 'subdistrict_tr' => 'MANYAS'],
            ['id' => 158, 'district_id' => 10, 'subdistrict_tr' => 'MARMARA'],
            ['id' => 159, 'district_id' => 10, 'subdistrict_tr' => 'SAVAŞTEPE'],
            ['id' => 160, 'district_id' => 10, 'subdistrict_tr' => 'SINDIRGI'],
            ['id' => 161, 'district_id' => 10, 'subdistrict_tr' => 'SUSURLUK'],
            //BARTIN
            ['id' => 162, 'district_id' => 74,'subdistrict_tr' => 'AMASRA'],
            ['id' => 163, 'district_id' => 74,'subdistrict_tr' => 'KURUCAŞİLE'],
            ['id' => 164, 'district_id' => 74,'subdistrict_tr' => 'MERKEZ'],
            ['id' => 165, 'district_id' => 74,'subdistrict_tr' => 'ULUS'],
// BATMAN
            ['id' => 166, 'district_id' => 72,'subdistrict_tr' => 'BEŞİRİ'],
            ['id' => 167, 'district_id' => 72,'subdistrict_tr' => 'GERCÜŞ'],
            ['id' => 168, 'district_id' => 72,'subdistrict_tr' => 'HASANKEYF'],
            ['id' => 169, 'district_id' => 72,'subdistrict_tr' => 'KOZLUK'],
            ['id' => 170, 'district_id' => 72,'subdistrict_tr' => 'MERKEZ'],
            ['id' => 171, 'district_id' => 72,'subdistrict_tr' => 'SASON'],
            //BAYBBURT
            ['id' => 172, 'district_id' => 69, 'subdistrict_tr' => 'AYDINTEPE'],
            ['id' => 173, 'district_id' => 69, 'subdistrict_tr' => 'DEMİRÖZÜ'],
            ['id' => 174, 'district_id' => 69, 'subdistrict_tr' => 'MERKEZ'],
            // BİLECİK
            ['id' => 175, 'district_id' => 11, 'subdistrict_tr' => 'BOZÜYÜK'],
            ['id' => 176, 'district_id' => 11, 'subdistrict_tr' => 'GÖLPAZARI'],
            ['id' => 177, 'district_id' => 11, 'subdistrict_tr' => 'İNHİSAR'],
            ['id' => 178, 'district_id' => 11, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 179, 'district_id' => 11, 'subdistrict_tr' => 'OSMANELİ'],
            ['id' => 180, 'district_id' => 11, 'subdistrict_tr' => 'PAZARYERİ'],
            ['id' => 181, 'district_id' => 11, 'subdistrict_tr' => 'SÖĞÜT'],
            ['id' => 182, 'district_id' => 11, 'subdistrict_tr' => 'YENİPAZAR'],
            //BİNGÖL
            ['id' => 183, 'district_id' => 12, 'subdistrict_tr' => 'ADAKLI'],
            ['id' => 184, 'district_id' => 12, 'subdistrict_tr' => 'GENÇ'],
            ['id' => 185, 'district_id' => 12, 'subdistrict_tr' => 'KARLIOVA'],
            ['id' => 186, 'district_id' => 12, 'subdistrict_tr' => 'KİĞI'],
            ['id' => 187, 'district_id' => 12, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 188, 'district_id' => 12, 'subdistrict_tr' => 'SOLHAN'],
            ['id' => 189, 'district_id' => 12, 'subdistrict_tr' => 'YAYLADERE'],
            ['id' => 190, 'district_id' => 12, 'subdistrict_tr' => 'YEDİSU'],
            //BİTLİS
            ['id' => 191, 'district_id' => 13, 'subdistrict_tr' => 'ADİLCEVAZ'],
            ['id' => 192, 'district_id' => 13, 'subdistrict_tr' => 'AHLAT'],
            ['id' => 193, 'district_id' => 13, 'subdistrict_tr' => 'GÜROYMAK'],
            ['id' => 194, 'district_id' => 13, 'subdistrict_tr' => 'HİZAN'],
            ['id' => 195, 'district_id' => 13, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 196, 'district_id' => 13, 'subdistrict_tr' => 'MUTKİ'],
            ['id' => 197, 'district_id' => 13, 'subdistrict_tr' => 'TATVAN'],
            //BOLU
            ['id' => 198, 'district_id' => 14, 'subdistrict_tr' => 'DÖRTDİVAN'],
            ['id' => 199, 'district_id' => 14, 'subdistrict_tr' => 'GEREDE'],
            ['id' => 200, 'district_id' => 14, 'subdistrict_tr' => 'GÖYNÜK'],
            ['id' => 201, 'district_id' => 14, 'subdistrict_tr' => 'KIBRISCIK'],
            ['id' => 202, 'district_id' => 14, 'subdistrict_tr' => 'MENGEN'],
            ['id' => 203, 'district_id' => 14, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 204, 'district_id' => 14, 'subdistrict_tr' => 'MUDURNU'],
            ['id' => 205, 'district_id' => 14, 'subdistrict_tr' => 'SEBEN'],
            ['id' => 206, 'district_id' => 14, 'subdistrict_tr' => 'YENİÇAĞA'],
            //BURDUR
            ['id' => 207, 'district_id' => 15, 'subdistrict_tr' => 'AĞLASUN'],
            ['id' => 208, 'district_id' => 15, 'subdistrict_tr' => 'ALTINYAYLA'],
            ['id' => 209, 'district_id' => 15, 'subdistrict_tr' => 'BUCAK'],
            ['id' => 210, 'district_id' => 15, 'subdistrict_tr' => 'ÇAVDIR'],
            ['id' => 211, 'district_id' => 15, 'subdistrict_tr' => 'ÇELTİKÇİ'],
            ['id' => 212, 'district_id' => 15, 'subdistrict_tr' => 'GÖLHİSAR'],
            ['id' => 213, 'district_id' => 15, 'subdistrict_tr' => 'KARAMANLI'],
            ['id' => 214, 'district_id' => 15, 'subdistrict_tr' => 'KEMER'],
            ['id' => 215, 'district_id' => 15, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 216, 'district_id' => 15, 'subdistrict_tr' => 'TEFENNİ'],
            ['id' => 217, 'district_id' => 15, 'subdistrict_tr' => 'YEŞİLOVA'],
            //BURSA
            ['id' => 218, 'district_id' => 16, 'subdistrict_tr' => 'BÜYÜKORHAN'],
            ['id' => 219, 'district_id' => 16, 'subdistrict_tr' => 'GEMLİK'],
            ['id' => 220, 'district_id' => 16, 'subdistrict_tr' => 'GÜRSU'],
            ['id' => 221, 'district_id' => 16, 'subdistrict_tr' => 'HARMANCIK'],
            ['id' => 222, 'district_id' => 16, 'subdistrict_tr' => 'İNEGÖL'],
            ['id' => 223, 'district_id' => 16, 'subdistrict_tr' => 'İZNİK'],
            ['id' => 224, 'district_id' => 16, 'subdistrict_tr' => 'KARACABEY'],
            ['id' => 225, 'district_id' => 16, 'subdistrict_tr' => 'KELES'],
            ['id' => 226, 'district_id' => 16, 'subdistrict_tr' => 'KESTEL'],
            ['id' => 227, 'district_id' => 16, 'subdistrict_tr' => 'MUDANYA'],
            ['id' => 228, 'district_id' => 16, 'subdistrict_tr' => 'MUSTAFAKEMALPAŞA'],
            ['id' => 229, 'district_id' => 16, 'subdistrict_tr' => 'NİLÜFER'],
            ['id' => 230, 'district_id' => 16, 'subdistrict_tr' => 'ORHANELİ'],
            ['id' => 231, 'district_id' => 16, 'subdistrict_tr' => 'ORHANGAZİ'],
            ['id' => 232, 'district_id' => 16, 'subdistrict_tr' => 'OSMANGAZİ'],
            ['id' => 233, 'district_id' => 16, 'subdistrict_tr' => 'YENİŞEHİR'],
            ['id' => 234, 'district_id' => 16, 'subdistrict_tr' => 'YILDIRIM'],
            //ÇANAKKALE
            ['id' => 235, 'district_id' => 17, 'subdistrict_tr' => 'AYVACIK'],
            ['id' => 236, 'district_id' => 17, 'subdistrict_tr' => 'BAYRAMİÇ'],
            ['id' => 237, 'district_id' => 17, 'subdistrict_tr' => 'BİGA'],
            ['id' => 238, 'district_id' => 17, 'subdistrict_tr' => 'BOZCAADA'],
            ['id' => 239, 'district_id' => 17, 'subdistrict_tr' => 'ÇAN'],
            ['id' => 240, 'district_id' => 17, 'subdistrict_tr' => 'ECEABAT'],
            ['id' => 241, 'district_id' => 17, 'subdistrict_tr' => 'EZİNE'],
            ['id' => 242, 'district_id' => 17, 'subdistrict_tr' => 'GELİBOLU'],
            ['id' => 243, 'district_id' => 17, 'subdistrict_tr' => 'GÖKÇEADA'],
            ['id' => 244, 'district_id' => 17, 'subdistrict_tr' => 'LAPSEKİ'],
            ['id' => 245, 'district_id' => 17, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 246, 'district_id' => 17, 'subdistrict_tr' => 'YENİCE'],
            //ÇANKIRI
            ['id' => 247, 'district_id' => 18, 'subdistrict_tr' => 'ATKARACALAR'],
            ['id' => 248, 'district_id' => 18, 'subdistrict_tr' => 'BAYRAMÖREN'],
            ['id' => 249, 'district_id' => 18, 'subdistrict_tr' => 'ÇERKEŞ'],
            ['id' => 250, 'district_id' => 18, 'subdistrict_tr' => 'ELDİVAN'],
            ['id' => 251, 'district_id' => 18, 'subdistrict_tr' => 'ILGAZ'],
            ['id' => 252, 'district_id' => 18, 'subdistrict_tr' => 'KIZILIRMAK'],
            ['id' => 253, 'district_id' => 18, 'subdistrict_tr' => 'KORGUN'],
            ['id' => 254, 'district_id' => 18, 'subdistrict_tr' => 'KURŞUNLU'],
            ['id' => 255, 'district_id' => 18, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 256, 'district_id' => 18, 'subdistrict_tr' => 'ORTA'],
            ['id' => 257, 'district_id' => 18, 'subdistrict_tr' => 'ŞABANÖZÜ'],
            ['id' => 258, 'district_id' => 18, 'subdistrict_tr' => 'YAPRAKLI'],
            //ÇORUM
            ['id' => 259, 'district_id' => 19, 'subdistrict_tr' => 'ALACA'],
            ['id' => 260, 'district_id' => 19, 'subdistrict_tr' => 'BAYAT'],
            ['id' => 261, 'district_id' => 19, 'subdistrict_tr' => 'BOĞAZKALE'],
            ['id' => 262, 'district_id' => 19, 'subdistrict_tr' => 'DODURGA'],
            ['id' => 263, 'district_id' => 19, 'subdistrict_tr' => 'İSKİLİP'],
            ['id' => 264, 'district_id' => 19, 'subdistrict_tr' => 'KARGI'],
            ['id' => 265, 'district_id' => 19, 'subdistrict_tr' => 'LAÇİN'],
            ['id' => 266, 'district_id' => 19, 'subdistrict_tr' => 'MECİTÖZÜ'],
            ['id' => 267, 'district_id' => 19, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 268, 'district_id' => 19, 'subdistrict_tr' => 'OĞUZLAR'],
            ['id' => 269, 'district_id' => 19, 'subdistrict_tr' => 'ORTAKÖY'],
            ['id' => 270, 'district_id' => 19, 'subdistrict_tr' => 'OSMANCIK'],
            ['id' => 271, 'district_id' => 19, 'subdistrict_tr' => 'SUNGURLU'],
            ['id' => 272, 'district_id' => 19, 'subdistrict_tr' => 'UĞURLUDAĞ'],
            //DENİZLİ
            ['id' => 273, 'district_id' => 20, 'subdistrict_tr' => 'ACIPAYAM'],
            ['id' => 274, 'district_id' => 20, 'subdistrict_tr' => 'BABADAĞ'],
            ['id' => 275, 'district_id' => 20, 'subdistrict_tr' => 'BAKLAN'],
            ['id' => 276, 'district_id' => 20, 'subdistrict_tr' => 'BEKİLLİ'],
            ['id' => 277, 'district_id' => 20, 'subdistrict_tr' => 'BEYAĞAÇ'],
            ['id' => 278, 'district_id' => 20, 'subdistrict_tr' => 'BOZKURT'],
            ['id' => 279, 'district_id' => 20, 'subdistrict_tr' => 'BULDAN'],
            ['id' => 280, 'district_id' => 20, 'subdistrict_tr' => 'ÇAL'],
            ['id' => 281, 'district_id' => 20, 'subdistrict_tr' => 'ÇAMELİ'],
            ['id' => 282, 'district_id' => 20, 'subdistrict_tr' => 'ÇARDAK'],
            ['id' => 283, 'district_id' => 20, 'subdistrict_tr' => 'ÇİVRİL'],
            ['id' => 284, 'district_id' => 20, 'subdistrict_tr' => 'GÜNEY'],
            ['id' => 285, 'district_id' => 20, 'subdistrict_tr' => 'HONAZ'],
            ['id' => 286, 'district_id' => 20, 'subdistrict_tr' => 'KALE'],
            ['id' => 287, 'district_id' => 20, 'subdistrict_tr' => 'MERKEZEFENDİ'],
            ['id' => 288, 'district_id' => 20, 'subdistrict_tr' => 'PAMUKKALE'],
            ['id' => 289, 'district_id' => 20, 'subdistrict_tr' => 'SARAYKÖY'],
            ['id' => 290, 'district_id' => 20, 'subdistrict_tr' => 'SERİNHİSAR'],
            ['id' => 291, 'district_id' => 20, 'subdistrict_tr' => 'TAVAS'],
            //diyarbakır
            ['id' => 292, 'district_id' => 21, 'subdistrict_tr' => 'BAĞLAR'],
            ['id' => 293, 'district_id' => 21, 'subdistrict_tr' => 'BİSMİL'],
            ['id' => 294, 'district_id' => 21, 'subdistrict_tr' => 'ÇERMİK'],
            ['id' => 295, 'district_id' => 21, 'subdistrict_tr' => 'ÇINAR'],
            ['id' => 296, 'district_id' => 21, 'subdistrict_tr' => 'ÇÜNGÜŞ'],
            ['id' => 297, 'district_id' => 21, 'subdistrict_tr' => 'DİCLE'],
            ['id' => 298, 'district_id' => 21, 'subdistrict_tr' => 'EĞİL'],
            ['id' => 299, 'district_id' => 21, 'subdistrict_tr' => 'ERGANİ'],
            ['id' => 300, 'district_id' => 21, 'subdistrict_tr' => 'HANİ'],
            ['id' => 301, 'district_id' => 21, 'subdistrict_tr' => 'HAZRO'],
            ['id' => 302, 'district_id' => 21, 'subdistrict_tr' => 'KAYAPINAR'],
            ['id' => 303, 'district_id' => 21, 'subdistrict_tr' => 'KOCAKÖY'],
            ['id' => 304, 'district_id' => 21, 'subdistrict_tr' => 'KULP'],
            ['id' => 305, 'district_id' => 21, 'subdistrict_tr' => 'LİCE'],
            ['id' => 306, 'district_id' => 21, 'subdistrict_tr' => 'SİLVAN'],
            ['id' => 307, 'district_id' => 21, 'subdistrict_tr' => 'SUR'],
            ['id' => 308, 'district_id' => 21, 'subdistrict_tr' => 'YENİŞEHİR'],
            //düzce
            ['id' => 309, 'district_id' => 81, 'subdistrict_tr' => 'AKÇAKOCA'],
            ['id' => 310, 'district_id' => 81, 'subdistrict_tr' => 'CUMAYERİ'],
            ['id' => 311, 'district_id' => 81, 'subdistrict_tr' => 'ÇİLİMLİ'],
            ['id' => 312, 'district_id' => 81, 'subdistrict_tr' => 'GÖLYAKA'],
            ['id' => 313, 'district_id' => 81, 'subdistrict_tr' => 'GÜMÜŞOVA'],
            ['id' => 314, 'district_id' => 81, 'subdistrict_tr' => 'KAYNAŞLI'],
            ['id' => 315, 'district_id' => 81, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 316, 'district_id' => 81, 'subdistrict_tr' => 'YIĞILCA'],
            //edirne
            ['id' => 317, 'district_id' => 22, 'subdistrict_tr' => 'ENEZ'],
            ['id' => 318, 'district_id' => 22, 'subdistrict_tr' => 'HAVSA'],
            ['id' => 319, 'district_id' => 22, 'subdistrict_tr' => 'İPSALA'],
            ['id' => 320, 'district_id' => 22, 'subdistrict_tr' => 'KEŞAN'],
            ['id' => 321, 'district_id' => 22, 'subdistrict_tr' => 'LALAPAŞA'],
            ['id' => 322, 'district_id' => 22, 'subdistrict_tr' => 'MERİÇ'],
            ['id' => 323, 'district_id' => 22, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 324, 'district_id' => 22, 'subdistrict_tr' => 'SÜLOĞLU'],
            ['id' => 325, 'district_id' => 22, 'subdistrict_tr' => 'UZUNKÖPRÜ'],
            //elazığ
            ['id' => 326, 'district_id' => 23, 'subdistrict_tr' => 'AĞIN'],
            ['id' => 327, 'district_id' => 23, 'subdistrict_tr' => 'ALACAKAYA'],
            ['id' => 328, 'district_id' => 23, 'subdistrict_tr' => 'ARICAK'],
            ['id' => 329, 'district_id' => 23, 'subdistrict_tr' => 'BASKİL'],
            ['id' => 330, 'district_id' => 23, 'subdistrict_tr' => 'KARAKOÇAN'],
            ['id' => 331, 'district_id' => 23, 'subdistrict_tr' => 'KEBAN'],
            ['id' => 332, 'district_id' => 23, 'subdistrict_tr' => 'KOVANCILAR'],
            ['id' => 333, 'district_id' => 23, 'subdistrict_tr' => 'MADEN'],
            ['id' => 334, 'district_id' => 23, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 335, 'district_id' => 23, 'subdistrict_tr' => 'PALU'],
            ['id' => 336, 'district_id' => 23, 'subdistrict_tr' => 'SİVRİCE'],
            //erzincan
            ['id' => 337, 'district_id' => 24, 'subdistrict_tr' => 'ÇAYIRLI'],
            ['id' => 338, 'district_id' => 24, 'subdistrict_tr' => 'İLİÇ'],
            ['id' => 339, 'district_id' => 24, 'subdistrict_tr' => 'KEMAH'],
            ['id' => 340, 'district_id' => 24, 'subdistrict_tr' => 'KEMALİYE'],
            ['id' => 341, 'district_id' => 24, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 342, 'district_id' => 24, 'subdistrict_tr' => 'OTLUKBELİ'],
            ['id' => 343, 'district_id' => 24, 'subdistrict_tr' => 'REFAHİYE'],
            ['id' => 344, 'district_id' => 24, 'subdistrict_tr' => 'TERCAN'],
            ['id' => 345, 'district_id' => 24, 'subdistrict_tr' => 'ÜZÜMLÜ'],
            //erzurum
            ['id' => 346, 'district_id' => 25, 'subdistrict_tr' => 'AŞKALE'],
            ['id' => 347, 'district_id' => 25, 'subdistrict_tr' => 'AZİZİYE'],
            ['id' => 348, 'district_id' => 25, 'subdistrict_tr' => 'ÇAT'],
            ['id' => 349, 'district_id' => 25, 'subdistrict_tr' => 'HINIS'],
            ['id' => 350, 'district_id' => 25, 'subdistrict_tr' => 'HORASAN'],
            ['id' => 351, 'district_id' => 25, 'subdistrict_tr' => 'İSPİR'],
            ['id' => 352, 'district_id' => 25, 'subdistrict_tr' => 'KARAÇOBAN'],
            ['id' => 353, 'district_id' => 25, 'subdistrict_tr' => 'KARAYAZI'],
            ['id' => 354, 'district_id' => 25, 'subdistrict_tr' => 'KÖPRÜKÖY'],
            ['id' => 355, 'district_id' => 25, 'subdistrict_tr' => 'NARMAN'],
            ['id' => 356, 'district_id' => 25, 'subdistrict_tr' => 'OLTU'],
            ['id' => 357, 'district_id' => 25, 'subdistrict_tr' => 'OLUR'],
            ['id' => 358, 'district_id' => 25, 'subdistrict_tr' => 'PALANDÖKEN'],
            ['id' => 359, 'district_id' => 25, 'subdistrict_tr' => 'PASİNLER'],
            ['id' => 360, 'district_id' => 25, 'subdistrict_tr' => 'PAZARYOLU'],
            ['id' => 361, 'district_id' => 25, 'subdistrict_tr' => 'ŞENKAYA'],
            ['id' => 362, 'district_id' => 25, 'subdistrict_tr' => 'TEKMAN'],
            ['id' => 363, 'district_id' => 25, 'subdistrict_tr' => 'TORTUM'],
            ['id' => 364, 'district_id' => 25, 'subdistrict_tr' => 'UZUNDERE'],
            ['id' => 365, 'district_id' => 25, 'subdistrict_tr' => 'YAKUTİYE'],
            //ESKİŞEHİR
            ['id' => 366, 'district_id' => 26, 'subdistrict_tr' => 'ALPU'],
            ['id' => 367, 'district_id' => 26, 'subdistrict_tr' => 'BEYLİKOVA'],
            ['id' => 368, 'district_id' => 26, 'subdistrict_tr' => 'ÇİFTELER'],
            ['id' => 369, 'district_id' => 26, 'subdistrict_tr' => 'GÜNYÜZÜ'],
            ['id' => 370, 'district_id' => 26, 'subdistrict_tr' => 'HAN'],
            ['id' => 371, 'district_id' => 26, 'subdistrict_tr' => 'İNÖNÜ'],
            ['id' => 372, 'district_id' => 26, 'subdistrict_tr' => 'MAHMUDİYE'],
            ['id' => 373, 'district_id' => 26, 'subdistrict_tr' => 'MİHALGAZİ'],
            ['id' => 374, 'district_id' => 26, 'subdistrict_tr' => 'MİHALIÇÇIK'],
            ['id' => 375, 'district_id' => 26, 'subdistrict_tr' => 'ODUNPAZARI'],
            ['id' => 376, 'district_id' => 26, 'subdistrict_tr' => 'SARICAKAYA'],
            ['id' => 377, 'district_id' => 26, 'subdistrict_tr' => 'SEYİTGAZİ'],
            ['id' => 378, 'district_id' => 26, 'subdistrict_tr' => 'SİVRİHİSAR'],
            ['id' => 379, 'district_id' => 26, 'subdistrict_tr' => 'TEPEBAŞI'],
            //GAZİANTEP
            ['id' => 380, 'district_id' => 27, 'subdistrict_tr' => 'ARABAN'],
            ['id' => 381, 'district_id' => 27, 'subdistrict_tr' => 'İSLAHİYE'],
            ['id' => 382, 'district_id' => 27, 'subdistrict_tr' => 'KARKAMIŞ'],
            ['id' => 383, 'district_id' => 27, 'subdistrict_tr' => 'NİZİP'],
            ['id' => 384, 'district_id' => 27, 'subdistrict_tr' => 'NURDAĞI'],
            ['id' => 385, 'district_id' => 27, 'subdistrict_tr' => 'OĞUZELİ'],
            ['id' => 386, 'district_id' => 27, 'subdistrict_tr' => 'ŞAHİNBEY'],
            ['id' => 387, 'district_id' => 27, 'subdistrict_tr' => 'ŞEHİTKAMİL'],
            ['id' => 388, 'district_id' => 27, 'subdistrict_tr' => 'YAVUZELİ'],
            //GİRESUN
            ['id' => 389, 'district_id' => 28, 'subdistrict_tr' => 'ALUCRA'],
            ['id' => 390, 'district_id' => 28, 'subdistrict_tr' => 'BULANCAK'],
            ['id' => 391, 'district_id' => 28, 'subdistrict_tr' => 'ÇAMOLUK'],
            ['id' => 392, 'district_id' => 28, 'subdistrict_tr' => 'ÇANAKÇI'],
            ['id' => 393, 'district_id' => 28, 'subdistrict_tr' => 'DERELİ'],
            ['id' => 394, 'district_id' => 28, 'subdistrict_tr' => 'DOĞANKENT'],
            ['id' => 395, 'district_id' => 28, 'subdistrict_tr' => 'ESPİYE'],
            ['id' => 396, 'district_id' => 28, 'subdistrict_tr' => 'EYNESİL'],
            ['id' => 397, 'district_id' => 28, 'subdistrict_tr' => 'GÖRELE'],
            ['id' => 398, 'district_id' => 28, 'subdistrict_tr' => 'GÜCE'],
            ['id' => 399, 'district_id' => 28, 'subdistrict_tr' => 'KEŞAP'],
            ['id' => 400, 'district_id' => 28, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 401, 'district_id' => 28, 'subdistrict_tr' => 'PİRAZİZ'],
            ['id' => 402, 'district_id' => 28, 'subdistrict_tr' => 'ŞEBİNKARAHİSAR'],
            ['id' => 403, 'district_id' => 28, 'subdistrict_tr' => 'TİREBOLU'],
            ['id' => 404, 'district_id' => 28, 'subdistrict_tr' => 'YAĞLIDERE'],
            //GÜMÜŞHANE
            ['id' => 405, 'district_id' => 29, 'subdistrict_tr' => 'KELKİT'],
            ['id' => 406, 'district_id' => 29, 'subdistrict_tr' => 'KÖSE'],
            ['id' => 407, 'district_id' => 29, 'subdistrict_tr' => 'KÜRTÜN'],
            ['id' => 408, 'district_id' => 29, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 409, 'district_id' => 29, 'subdistrict_tr' => 'ŞİRAN'],
            ['id' => 410, 'district_id' => 29, 'subdistrict_tr' => 'TORUL'],
            // HAKKARİ
            ['id' => 411, 'district_id' => 30, 'subdistrict_tr' => 'ÇUKURCA'],
            ['id' => 412, 'district_id' => 30, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 413, 'district_id' => 30, 'subdistrict_tr' => 'ŞEMDİNLİ'],
            ['id' => 414, 'district_id' => 30, 'subdistrict_tr' => 'YÜKSEKOVA'],
            //HATAY
            ['id' => 415, 'district_id' => 31, 'subdistrict_tr' => 'ALTINÖZÜ'],
            ['id' => 416, 'district_id' => 31, 'subdistrict_tr' => 'ANTAKYA'],
            ['id' => 417, 'district_id' => 31, 'subdistrict_tr' => 'ARSUZ'],
            ['id' => 418, 'district_id' => 31, 'subdistrict_tr' => 'BELEN'],
            ['id' => 419, 'district_id' => 31, 'subdistrict_tr' => 'DEFNE'],
            ['id' => 420, 'district_id' => 31, 'subdistrict_tr' => 'DÖRTYOL'],
            ['id' => 421, 'district_id' => 31, 'subdistrict_tr' => 'ERZİN'],
            ['id' => 422, 'district_id' => 31, 'subdistrict_tr' => 'HASSA'],
            ['id' => 423, 'district_id' => 31, 'subdistrict_tr' => 'İSKENDERUN'],
            ['id' => 424, 'district_id' => 31, 'subdistrict_tr' => 'KIRIKHAN'],
            ['id' => 425, 'district_id' => 31, 'subdistrict_tr' => 'KUMLU'],
            ['id' => 426, 'district_id' => 31, 'subdistrict_tr' => 'PAYAS'],
            ['id' => 427, 'district_id' => 31, 'subdistrict_tr' => 'REYHANLI'],
            ['id' => 428, 'district_id' => 31, 'subdistrict_tr' => 'SAMANDAĞ'],
            ['id' => 429, 'district_id' => 31, 'subdistrict_tr' => 'YAYLADAĞI'],
            //
            ['id' => 430, 'district_id' => 76, 'subdistrict_tr' => 'ARALIK'],
            ['id' => 431, 'district_id' => 76, 'subdistrict_tr' => 'KARAKOYUNLU'],
            ['id' => 432, 'district_id' => 76, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 433, 'district_id' => 76, 'subdistrict_tr' => 'TUZLUCA'],

            ['id' => 434, 'district_id' => 32, 'subdistrict_tr' => 'AKSU'],
            ['id' => 435, 'district_id' => 32, 'subdistrict_tr' => 'ATABEY'],
            ['id' => 436, 'district_id' => 32, 'subdistrict_tr' => 'EĞİRDİR'],
            ['id' => 437, 'district_id' => 32, 'subdistrict_tr' => 'GELENDOST'],
            ['id' => 438, 'district_id' => 32, 'subdistrict_tr' => 'GÖNEN'],
            ['id' => 439, 'district_id' => 32, 'subdistrict_tr' => 'KEÇİBORLU'],
            ['id' => 440, 'district_id' => 32, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 441, 'district_id' => 32, 'subdistrict_tr' => 'SENİRKENT'],
            ['id' => 442, 'district_id' => 32, 'subdistrict_tr' => 'SÜTÇÜLER'],
            ['id' => 443, 'district_id' => 32, 'subdistrict_tr' => 'ŞARKİKARAAĞAÇ'],
            ['id' => 444, 'district_id' => 32, 'subdistrict_tr' => 'ULUBORLU'],
            ['id' => 445, 'district_id' => 32, 'subdistrict_tr' => 'YALVAÇ'],
            ['id' => 446, 'district_id' => 32, 'subdistrict_tr' => 'YENİŞARBADEMLİ'],
            //İSTANBUL
            ['id' => 447, 'district_id' => 34, 'subdistrict_tr' => 'ADALAR'],
            ['id' => 448, 'district_id' => 34, 'subdistrict_tr' => 'ARNAVUTKÖY'],
            ['id' => 449, 'district_id' => 34, 'subdistrict_tr' => 'ATAŞEHİR'],
            ['id' => 450, 'district_id' => 34, 'subdistrict_tr' => 'AVCILAR'],
            ['id' => 451, 'district_id' => 34, 'subdistrict_tr' => 'BAĞCILAR'],
            ['id' => 452, 'district_id' => 34, 'subdistrict_tr' => 'BAHÇELİEVLER'],
            ['id' => 453, 'district_id' => 34, 'subdistrict_tr' => 'BAKIRKÖY'],
            ['id' => 454, 'district_id' => 34, 'subdistrict_tr' => 'BAŞAKŞEHİR'],
            ['id' => 455, 'district_id' => 34, 'subdistrict_tr' => 'BAYRAMPAŞA'],
            ['id' => 456, 'district_id' => 34, 'subdistrict_tr' => 'BEŞİKTAŞ'],
            ['id' => 457, 'district_id' => 34, 'subdistrict_tr' => 'BEYKOZ'],
            ['id' => 458, 'district_id' => 34, 'subdistrict_tr' => 'BEYLİKDÜZÜ'],
            ['id' => 459, 'district_id' => 34, 'subdistrict_tr' => 'BEYOĞLU'],
            ['id' => 460, 'district_id' => 34, 'subdistrict_tr' => 'BÜYÜKÇEKMECE'],
            ['id' => 461, 'district_id' => 34, 'subdistrict_tr' => 'ÇATALCA'],
            ['id' => 462, 'district_id' => 34, 'subdistrict_tr' => 'ÇEKMEKÖY'],
            ['id' => 463, 'district_id' => 34, 'subdistrict_tr' => 'ESENLER'],
            ['id' => 464, 'district_id' => 34, 'subdistrict_tr' => 'ESENYURT'],
            ['id' => 465, 'district_id' => 34, 'subdistrict_tr' => 'EYÜPSULTAN'],
            ['id' => 466, 'district_id' => 34, 'subdistrict_tr' => 'FATİH'],
            ['id' => 467, 'district_id' => 34, 'subdistrict_tr' => 'GAZİOSMANPAŞA'],
            ['id' => 468, 'district_id' => 34, 'subdistrict_tr' => 'GÜNGÖREN'],
            ['id' => 469, 'district_id' => 34, 'subdistrict_tr' => 'KADIKÖY'],
            ['id' => 470, 'district_id' => 34, 'subdistrict_tr' => 'KAĞITHANE'],
            ['id' => 471, 'district_id' => 34, 'subdistrict_tr' => 'KARTAL'],
            ['id' => 472, 'district_id' => 34, 'subdistrict_tr' => 'KÜÇÜKÇEKMECE'],
            ['id' => 473, 'district_id' => 34, 'subdistrict_tr' => 'MALTEPE'],
            ['id' => 474, 'district_id' => 34, 'subdistrict_tr' => 'PENDİK'],
            ['id' => 475, 'district_id' => 34, 'subdistrict_tr' => 'SANCAKTEPE'],
            ['id' => 476, 'district_id' => 34, 'subdistrict_tr' => 'SARIYER'],
            ['id' => 477, 'district_id' => 34, 'subdistrict_tr' => 'SİLİVRİ'],
            ['id' => 478, 'district_id' => 34, 'subdistrict_tr' => 'SULTANBEYLİ'],
            ['id' => 479, 'district_id' => 34, 'subdistrict_tr' => 'SULTANGAZİ'],
            ['id' => 480, 'district_id' => 34, 'subdistrict_tr' => 'ŞİLE'],
            ['id' => 481, 'district_id' => 34, 'subdistrict_tr' => 'ŞİŞLİ'],
            ['id' => 482, 'district_id' => 34, 'subdistrict_tr' => 'TUZLA'],
            ['id' => 483, 'district_id' => 34, 'subdistrict_tr' => 'ÜMRANİYE'],
            ['id' => 484, 'district_id' => 34, 'subdistrict_tr' => 'ÜSKÜDAR'],
            ['id' => 485, 'district_id' => 34, 'subdistrict_tr' => 'ZEYTİNBURNU'],
            //İZMİR
            ['id' => 486, 'district_id' => 35, 'subdistrict_tr' => 'ALİAĞA'],
            ['id' => 487, 'district_id' => 35, 'subdistrict_tr' => 'BALÇOVA'],
            ['id' => 488, 'district_id' => 35, 'subdistrict_tr' => 'BAYINDIR'],
            ['id' => 489, 'district_id' => 35, 'subdistrict_tr' => 'BAYRAKLI'],
            ['id' => 490, 'district_id' => 35, 'subdistrict_tr' => 'BERGAMA'],
            ['id' => 491, 'district_id' => 35, 'subdistrict_tr' => 'BEYDAĞ'],
            ['id' => 492, 'district_id' => 35, 'subdistrict_tr' => 'BORNOVA'],
            ['id' => 493, 'district_id' => 35, 'subdistrict_tr' => 'BUCA'],
            ['id' => 494, 'district_id' => 35, 'subdistrict_tr' => 'ÇEŞME'],
            ['id' => 495, 'district_id' => 35, 'subdistrict_tr' => 'ÇİĞLİ'],
            ['id' => 496, 'district_id' => 35, 'subdistrict_tr' => 'DİKİLİ'],
            ['id' => 497, 'district_id' => 35, 'subdistrict_tr' => 'FOÇA'],
            ['id' => 498, 'district_id' => 35, 'subdistrict_tr' => 'GAZİEMİR'],
            ['id' => 499, 'district_id' => 35, 'subdistrict_tr' => 'GÜZELBAHÇE'],
            ['id' => 500, 'district_id' => 35, 'subdistrict_tr' => 'KARABAĞLAR'],
            ['id' => 501, 'district_id' => 35, 'subdistrict_tr' => 'KARABURUN'],
            ['id' => 502, 'district_id' => 35, 'subdistrict_tr' => 'KARŞIYAKA'],
            ['id' => 503, 'district_id' => 35, 'subdistrict_tr' => 'KEMALPAŞA'],
            ['id' => 504, 'district_id' => 35, 'subdistrict_tr' => 'KINIK'],
            ['id' => 505, 'district_id' => 35, 'subdistrict_tr' => 'KİRAZ'],
            ['id' => 506, 'district_id' => 35, 'subdistrict_tr' => 'KONAK'],
            ['id' => 507, 'district_id' => 35, 'subdistrict_tr' => 'MENDERES'],
            ['id' => 508, 'district_id' => 35, 'subdistrict_tr' => 'MENEMEN'],
            ['id' => 509, 'district_id' => 35, 'subdistrict_tr' => 'NARLIDERE'],
            ['id' => 510, 'district_id' => 35, 'subdistrict_tr' => 'ÖDEMİŞ'],
            ['id' => 511, 'district_id' => 35, 'subdistrict_tr' => 'SEFERİHİSAR'],
            ['id' => 512, 'district_id' => 35, 'subdistrict_tr' => 'SELÇUK'],
            ['id' => 513, 'district_id' => 35, 'subdistrict_tr' => 'TİRE'],
            ['id' => 514, 'district_id' => 35, 'subdistrict_tr' => 'TORBALI'],
            ['id' => 515, 'district_id' => 35, 'subdistrict_tr' => 'URLA'],
            //KAHRAMAN MARAŞ
            ['id' => 516, 'district_id' => 46, 'subdistrict_tr' => 'AfŞİN'],
            ['id' => 517, 'district_id' => 46, 'subdistrict_tr' => 'ANDIRIN'],
            ['id' => 518, 'district_id' => 46, 'subdistrict_tr' => 'ÇAĞLAYANCERİT'],
            ['id' => 519, 'district_id' => 46, 'subdistrict_tr' => 'DULKADİROĞLU'],
            ['id' => 520, 'district_id' => 46, 'subdistrict_tr' => 'EKİNÖZÜ'],
            ['id' => 521, 'district_id' => 46, 'subdistrict_tr' => 'ELBİSTAN'],
            ['id' => 522, 'district_id' => 46, 'subdistrict_tr' => 'GÖKSUN'],
            ['id' => 523, 'district_id' => 46, 'subdistrict_tr' => 'NURHAK'],
            ['id' => 524, 'district_id' => 46, 'subdistrict_tr' => 'ONİKİŞUBAT'],
            ['id' => 525, 'district_id' => 46, 'subdistrict_tr' => 'PAZARCIK'],
            ['id' => 526, 'district_id' => 46, 'subdistrict_tr' => 'TÜRKOĞLU'],
            //KARABÜK
            ['id' => 527, 'district_id' => 78, 'subdistrict_tr' => 'EFLANİ'],
            ['id' => 528, 'district_id' => 78, 'subdistrict_tr' => 'ESKİPAZAR'],
            ['id' => 529, 'district_id' => 78, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 530, 'district_id' => 78, 'subdistrict_tr' => 'OVACIK'],
            ['id' => 531, 'district_id' => 78, 'subdistrict_tr' => 'SAFRANBOLU'],
            ['id' => 532, 'district_id' => 78, 'subdistrict_tr' => 'YENİCE'],
            //karaman
            ['id' => 533, 'district_id' => 70, 'subdistrict_tr' => 'AYRANCI'],
            ['id' => 534, 'district_id' => 70, 'subdistrict_tr' => 'BAŞYAYLA'],
            ['id' => 535, 'district_id' => 70, 'subdistrict_tr' => 'ERMENEK'],
            ['id' => 536, 'district_id' => 70, 'subdistrict_tr' => 'KAZIMKARABEKİR'],
            ['id' => 537, 'district_id' => 70, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 538, 'district_id' => 70, 'subdistrict_tr' => 'SARIVELİLER'],
            //KARS
            ['id' => 539, 'district_id' => 36, 'subdistrict_tr' => 'AKYAKA'],
            ['id' => 540, 'district_id' => 36, 'subdistrict_tr' => 'ARPAÇAY'],
            ['id' => 541, 'district_id' => 36, 'subdistrict_tr' => 'DİGOR'],
            ['id' => 542, 'district_id' => 36, 'subdistrict_tr' => 'KAĞIZMAN'],
            ['id' => 543, 'district_id' => 36, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 544, 'district_id' => 36, 'subdistrict_tr' => 'SARIKAMIŞ'],
            ['id' => 545, 'district_id' => 36, 'subdistrict_tr' => 'SELİM'],
            ['id' => 546, 'district_id' => 36, 'subdistrict_tr' => 'SUSUZ'],
            //KASTAMONU
            ['id' => 547, 'district_id' => 37, 'subdistrict_tr' => 'ABANA'],
            ['id' => 548, 'district_id' => 37, 'subdistrict_tr' => 'AĞLI'],
            ['id' => 549, 'district_id' => 37, 'subdistrict_tr' => 'ARAÇ'],
            ['id' => 550, 'district_id' => 37, 'subdistrict_tr' => 'AZDAVAY'],
            ['id' => 551, 'district_id' => 37, 'subdistrict_tr' => 'BOZKURT'],
            ['id' => 552, 'district_id' => 37, 'subdistrict_tr' => 'CİDE'],
            ['id' => 553, 'district_id' => 37, 'subdistrict_tr' => 'ÇATALZEYTİN'],
            ['id' => 554, 'district_id' => 37, 'subdistrict_tr' => 'DADAY'],
            ['id' => 555, 'district_id' => 37, 'subdistrict_tr' => 'DEVREKANİ'],
            ['id' => 556, 'district_id' => 37, 'subdistrict_tr' => 'DOĞANYURT'],
            ['id' => 557, 'district_id' => 37, 'subdistrict_tr' => 'HANÖNÜ'],
            ['id' => 558, 'district_id' => 37, 'subdistrict_tr' => 'İHSANGAZİ'],
            ['id' => 559, 'district_id' => 37, 'subdistrict_tr' => 'İNEBOLU'],
            ['id' => 560, 'district_id' => 37, 'subdistrict_tr' => 'KÜRE'],
            ['id' => 561, 'district_id' => 37, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 562, 'district_id' => 37, 'subdistrict_tr' => 'PINARBAŞI'],
            ['id' => 563, 'district_id' => 37, 'subdistrict_tr' => 'SEYDİLER'],
            ['id' => 564, 'district_id' => 37, 'subdistrict_tr' => 'ŞENPAZAR'],
            ['id' => 565, 'district_id' => 37, 'subdistrict_tr' => 'TAŞKÖPRÜ'],
            ['id' => 566, 'district_id' => 37, 'subdistrict_tr' => 'TOSYA'],
            //KAYSERİ
            ['id' => 567, 'district_id' => 38, 'subdistrict_tr' => 'AKKIŞLA'],
            ['id' => 568, 'district_id' => 38, 'subdistrict_tr' => 'BÜNYAN'],
            ['id' => 569, 'district_id' => 38, 'subdistrict_tr' => 'DEVELİ'],
            ['id' => 570, 'district_id' => 38, 'subdistrict_tr' => 'FELAHİYE'],
            ['id' => 571, 'district_id' => 38, 'subdistrict_tr' => 'HACILAR'],
            ['id' => 572, 'district_id' => 38, 'subdistrict_tr' => 'İNCESU'],
            ['id' => 573, 'district_id' => 38, 'subdistrict_tr' => 'KOCASİNAN'],
            ['id' => 574, 'district_id' => 38, 'subdistrict_tr' => 'MELİKGAZİ'],
            ['id' => 575, 'district_id' => 38, 'subdistrict_tr' => 'ÖZVATAN'],
            ['id' => 576, 'district_id' => 38, 'subdistrict_tr' => 'PINARBAŞI'],
            ['id' => 577, 'district_id' => 38, 'subdistrict_tr' => 'SARIOĞLAN'],
            ['id' => 578, 'district_id' => 38, 'subdistrict_tr' => 'SARIZ'],
            ['id' => 579, 'district_id' => 38, 'subdistrict_tr' => 'TALAS'],
            ['id' => 580, 'district_id' => 38, 'subdistrict_tr' => 'TOMARZA'],
            ['id' => 581, 'district_id' => 38, 'subdistrict_tr' => 'YAHYALI'],
            ['id' => 582, 'district_id' => 38, 'subdistrict_tr' => 'YEŞİLHİSAR'],
            //KIRIKKALE
            ['id' => 583, 'district_id' => 71, 'subdistrict_tr' => 'BAHŞİLİ'],
            ['id' => 584, 'district_id' => 71, 'subdistrict_tr' => 'BALIŞEYH'],
            ['id' => 585, 'district_id' => 71, 'subdistrict_tr' => 'ÇELEBİ'],
            ['id' => 586, 'district_id' => 71, 'subdistrict_tr' => 'DELİCE'],
            ['id' => 587, 'district_id' => 71, 'subdistrict_tr' => 'KARAKEÇİLİ'],
            ['id' => 588, 'district_id' => 71, 'subdistrict_tr' => 'KESKİN'],
            ['id' => 589, 'district_id' => 71, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 590, 'district_id' => 71, 'subdistrict_tr' => 'SULAKYURT'],
            ['id' => 591, 'district_id' => 71, 'subdistrict_tr' => 'YAHŞİHAN'],
            //KIRKLARELİ
            ['id' => 592, 'district_id' => 39, 'subdistrict_tr' => 'BABAESKİ'],
            ['id' => 593, 'district_id' => 39, 'subdistrict_tr' => 'DEMİRKÖY'],
            ['id' => 594, 'district_id' => 39, 'subdistrict_tr' => 'KOFÇAZ'],
            ['id' => 595, 'district_id' => 39, 'subdistrict_tr' => 'LÜLEBURGAZ'],
            ['id' => 596, 'district_id' => 39, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 597, 'district_id' => 39, 'subdistrict_tr' => 'PEHLİVANKÖY'],
            ['id' => 598, 'district_id' => 39, 'subdistrict_tr' => 'PINARHİSAR'],
            ['id' => 599, 'district_id' => 39, 'subdistrict_tr' => 'VİZE'],
            //KIRŞEHİR
            ['id' => 600, 'district_id' => 40, 'subdistrict_tr' => 'AKÇAKENT'],
            ['id' => 601, 'district_id' => 40, 'subdistrict_tr' => 'AKPINAR'],
            ['id' => 602, 'district_id' => 40, 'subdistrict_tr' => 'BOZTEPE'],
            ['id' => 603, 'district_id' => 40, 'subdistrict_tr' => 'ÇİÇEKDAĞI'],
            ['id' => 604, 'district_id' => 40, 'subdistrict_tr' => 'KAMAN'],
            ['id' => 605, 'district_id' => 40, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 606, 'district_id' => 40, 'subdistrict_tr' => 'MUCUR'],
            //KİLİS
            ['id' => 607, 'district_id' =>79 , 'subdistrict_tr' => 'ELBEYLİ'],
            ['id' => 608, 'district_id' =>79 , 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 609, 'district_id' =>79 , 'subdistrict_tr' => 'MUSABEYLİ'],
            ['id' => 610, 'district_id' =>79 , 'subdistrict_tr' => 'POLATELİ'],
            //KOCAELİ
            ['id' => 611, 'district_id' =>41 , 'subdistrict_tr' => 'BAŞİSKELE'],
            ['id' => 612, 'district_id' =>41 , 'subdistrict_tr' => 'ÇAYIROVA'],
            ['id' => 613, 'district_id' =>41 , 'subdistrict_tr' => 'DARICA'],
            ['id' => 614, 'district_id' =>41 , 'subdistrict_tr' => 'DERİNCE'],
            ['id' => 615, 'district_id' =>41 , 'subdistrict_tr' => 'DİLOVASI'],
            ['id' => 616, 'district_id' =>41 , 'subdistrict_tr' => 'GEBZE'],
            ['id' => 617, 'district_id' =>41 , 'subdistrict_tr' => 'GÖLCÜK'],
            ['id' => 618, 'district_id' =>41 , 'subdistrict_tr' => 'İZMİT'],
            ['id' => 619, 'district_id' =>41 , 'subdistrict_tr' => 'KANDIRA'],
            ['id' => 620, 'district_id' =>41 , 'subdistrict_tr' => 'KARAMÜRSEL'],
            ['id' => 621, 'district_id' =>41 , 'subdistrict_tr' => 'KARTEPE'],
            ['id' => 622, 'district_id' =>41 , 'subdistrict_tr' => 'KÖRFEZ'],
            //KONYA
            ['id' => 623, 'district_id' =>42 , 'subdistrict_tr' => 'AHIRLI'],
            ['id' => 624, 'district_id' =>42 , 'subdistrict_tr' => 'AKÖREN'],
            ['id' => 625, 'district_id' =>42 , 'subdistrict_tr' => 'AKŞEHİR'],
            ['id' => 626, 'district_id' =>42 , 'subdistrict_tr' => 'ALTINEKİN'],
            ['id' => 627, 'district_id' =>42 , 'subdistrict_tr' => 'BEYŞEHİR'],
            ['id' => 628, 'district_id' =>42 , 'subdistrict_tr' => 'BOZKIR'],
            ['id' => 629, 'district_id' =>42 , 'subdistrict_tr' => 'CİHANBEYLİ'],
            ['id' => 630, 'district_id' =>42 , 'subdistrict_tr' => 'ÇELTİK'],
            ['id' => 631, 'district_id' =>42 , 'subdistrict_tr' => 'ÇUMRA'],
            ['id' => 632, 'district_id' =>42 , 'subdistrict_tr' => 'DERBENT'],
            ['id' => 633, 'district_id' =>42 , 'subdistrict_tr' => 'DEREBUCAK'],
            ['id' => 634, 'district_id' =>42 , 'subdistrict_tr' => 'DOĞANHİSAR'],
            ['id' => 635, 'district_id' =>42 , 'subdistrict_tr' => 'EMİRGAZİ'],
            ['id' => 636, 'district_id' =>42 , 'subdistrict_tr' => 'EREĞLİ'],
            ['id' => 637, 'district_id' =>42 , 'subdistrict_tr' => 'GÜNEYSINIR'],
            ['id' => 638, 'district_id' =>42 , 'subdistrict_tr' => 'HADİM'],
            ['id' => 639, 'district_id' =>42 , 'subdistrict_tr' => 'HALKAPINAR'],
            ['id' => 640, 'district_id' =>42 , 'subdistrict_tr' => 'HÜYÜK'],
            ['id' => 641, 'district_id' =>42 , 'subdistrict_tr' => 'ILGIN'],
            ['id' => 642, 'district_id' =>42 , 'subdistrict_tr' => 'KADINHANI'],
            ['id' => 643, 'district_id' =>42 , 'subdistrict_tr' => 'KARAPINAR'],
            ['id' => 644, 'district_id' =>42 , 'subdistrict_tr' => 'KARATAY'],
            ['id' => 645, 'district_id' =>42 , 'subdistrict_tr' => 'KULU'],
            ['id' => 646, 'district_id' =>42 , 'subdistrict_tr' => 'MERAM'],
            ['id' => 647, 'district_id' =>42 , 'subdistrict_tr' => 'SARAYÖNÜ'],
            ['id' => 648, 'district_id' =>42 , 'subdistrict_tr' => 'SELÇUKLU'],
            ['id' => 649, 'district_id' =>42 , 'subdistrict_tr' => 'SEYDİŞEHİR'],
            ['id' => 650, 'district_id' =>42 , 'subdistrict_tr' => 'TAŞKENT'],
            ['id' => 651, 'district_id' =>42 , 'subdistrict_tr' => 'TUZLUKÇU'],
            ['id' => 652, 'district_id' =>42 , 'subdistrict_tr' => 'YALIHÜYÜK'],
            ['id' => 653, 'district_id' =>42 , 'subdistrict_tr' => 'YUNAK'],
            //KÜTAHYA
            ['id' => 654, 'district_id' => 43, 'subdistrict_tr' => 'ALTINTAŞ'],
            ['id' => 655, 'district_id' => 43, 'subdistrict_tr' => 'ASLANAPA'],
            ['id' => 656, 'district_id' => 43, 'subdistrict_tr' => 'ÇAVDARHİSAR'],
            ['id' => 657, 'district_id' => 43, 'subdistrict_tr' => 'DOMANİÇ'],
            ['id' => 658, 'district_id' => 43, 'subdistrict_tr' => 'DUMLUPINAR'],
            ['id' => 659, 'district_id' => 43, 'subdistrict_tr' => 'EMET'],
            ['id' => 660, 'district_id' => 43, 'subdistrict_tr' => 'GEDİZ'],
            ['id' => 661, 'district_id' => 43, 'subdistrict_tr' => 'HİSARCIK'],
            ['id' => 662, 'district_id' => 43, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 663, 'district_id' => 43, 'subdistrict_tr' => 'PAZARLAR'],
            ['id' => 664, 'district_id' => 43, 'subdistrict_tr' => 'SİMAV'],
            ['id' => 665, 'district_id' => 43, 'subdistrict_tr' => 'ŞAPHANE'],
            ['id' => 666, 'district_id' => 43, 'subdistrict_tr' => 'TAVŞANLI'],
            //MALATYA
            ['id' => 667, 'district_id' => 44, 'subdistrict_tr' => 'AKÇADAĞ'],
            ['id' => 668, 'district_id' => 44, 'subdistrict_tr' => 'ARAPGİR'],
            ['id' => 669, 'district_id' => 44, 'subdistrict_tr' => 'ARGUVAN'],
            ['id' => 670, 'district_id' => 44, 'subdistrict_tr' => 'BATTALGAZİ'],
            ['id' => 671, 'district_id' => 44, 'subdistrict_tr' => 'DARENDE'],
            ['id' => 672, 'district_id' => 44, 'subdistrict_tr' => 'DOĞANŞEHİR'],
            ['id' => 673, 'district_id' => 44, 'subdistrict_tr' => 'DOĞANYOL'],
            ['id' => 674, 'district_id' => 44, 'subdistrict_tr' => 'HEKİMHAN'],
            ['id' => 675, 'district_id' => 44, 'subdistrict_tr' => 'KALE'],
            ['id' => 676, 'district_id' => 44, 'subdistrict_tr' => 'KULUNCAK'],
            ['id' => 677, 'district_id' => 44, 'subdistrict_tr' => 'PÜTÜRGE'],
            ['id' => 678, 'district_id' => 44, 'subdistrict_tr' => 'YAZIHAN'],
            ['id' => 679, 'district_id' => 44, 'subdistrict_tr' => 'YEŞİLYURT'],
            //MANİSA
            ['id' => 680, 'district_id' => 45, 'subdistrict_tr' => 'AHMETLİ'],
            ['id' => 681, 'district_id' => 45, 'subdistrict_tr' => 'AKHİSAR'],
            ['id' => 682, 'district_id' => 45, 'subdistrict_tr' => 'ALAŞEHİR'],
            ['id' => 683, 'district_id' => 45, 'subdistrict_tr' => 'DEMİRCİ'],
            ['id' => 684, 'district_id' => 45, 'subdistrict_tr' => 'GÖLMARMARA'],
            ['id' => 685, 'district_id' => 45, 'subdistrict_tr' => 'GÖRDES'],
            ['id' => 686, 'district_id' => 45, 'subdistrict_tr' => 'KIRKAĞAÇ'],
            ['id' => 687, 'district_id' => 45, 'subdistrict_tr' => 'KÖPRÜBAŞI'],
            ['id' => 688, 'district_id' => 45, 'subdistrict_tr' => 'KULA'],
            ['id' => 689, 'district_id' => 45, 'subdistrict_tr' => 'SALİHLİ'],
            ['id' => 690, 'district_id' => 45, 'subdistrict_tr' => 'SARIGÖL'],
            ['id' => 691, 'district_id' => 45, 'subdistrict_tr' => 'SARUHANLI'],
            ['id' => 692, 'district_id' => 45, 'subdistrict_tr' => 'SELENDİ'],
            ['id' => 693, 'district_id' => 45, 'subdistrict_tr' => 'SOMA'],
            ['id' => 694, 'district_id' => 45, 'subdistrict_tr' => 'ŞEHZADELER'],
            ['id' => 695, 'district_id' => 45, 'subdistrict_tr' => 'TURGUTLU'],
            ['id' => 696, 'district_id' => 45, 'subdistrict_tr' => 'YUNUSEMRE'],
            //MARDİN
            ['id' => 697, 'district_id' => 47, 'subdistrict_tr' => 'ARTUKLU'],
            ['id' => 698, 'district_id' => 47, 'subdistrict_tr' => 'DARGEÇİT'],
            ['id' => 699, 'district_id' => 47, 'subdistrict_tr' => 'DERİK'],
            ['id' => 700, 'district_id' => 47, 'subdistrict_tr' => 'KIZILTEPE'],
            ['id' => 701, 'district_id' => 47, 'subdistrict_tr' => 'MAZIDAĞI'],
            ['id' => 702, 'district_id' => 47, 'subdistrict_tr' => 'MİDYAT'],
            ['id' => 703, 'district_id' => 47, 'subdistrict_tr' => 'NUSAYBİN'],
            ['id' => 704, 'district_id' => 47, 'subdistrict_tr' => 'ÖMERLİ'],
            ['id' => 705, 'district_id' => 47, 'subdistrict_tr' => 'SAVUR'],
            ['id' => 706, 'district_id' => 47, 'subdistrict_tr' => 'YEŞİLLİ'],
            //MERSİN
            ['id' => 707, 'district_id' => 33, 'subdistrict_tr' => 'AKDENİZ'],
            ['id' => 708, 'district_id' => 33, 'subdistrict_tr' => 'ANAMUR'],
            ['id' => 709, 'district_id' => 33, 'subdistrict_tr' => 'AYDINCIK'],
            ['id' => 710, 'district_id' => 33, 'subdistrict_tr' => 'BOZYAZI'],
            ['id' => 711, 'district_id' => 33, 'subdistrict_tr' => 'ÇAMLIYAYLA'],
            ['id' => 712, 'district_id' => 33, 'subdistrict_tr' => 'ERDEMLİ'],
            ['id' => 713, 'district_id' => 33, 'subdistrict_tr' => 'GÜLNAR'],
            ['id' => 714, 'district_id' => 33, 'subdistrict_tr' => 'MEZİTLİ'],
            ['id' => 715, 'district_id' => 33, 'subdistrict_tr' => 'MUT'],
            ['id' => 716, 'district_id' => 33, 'subdistrict_tr' => 'SİLİFKE'],
            ['id' => 717, 'district_id' => 33, 'subdistrict_tr' => 'TARSUS'],
            ['id' => 718, 'district_id' => 33, 'subdistrict_tr' => 'TOROSLAR'],
            ['id' => 719, 'district_id' => 33, 'subdistrict_tr' => 'YENİŞEHİR'],
            //MUĞLA
            ['id' => 720, 'district_id' => 48, 'subdistrict_tr' => 'BODRUM'],
            ['id' => 721, 'district_id' => 48, 'subdistrict_tr' => 'DALAMAN'],
            ['id' => 722, 'district_id' => 48, 'subdistrict_tr' => 'DATÇA'],
            ['id' => 723, 'district_id' => 48, 'subdistrict_tr' => 'FETHİYE'],
            ['id' => 724, 'district_id' => 48, 'subdistrict_tr' => 'KAVAKLIDERE'],
            ['id' => 725, 'district_id' => 48, 'subdistrict_tr' => 'KÖYCEĞİZ'],
            ['id' => 726, 'district_id' => 48, 'subdistrict_tr' => 'MARMARİS'],
            ['id' => 727, 'district_id' => 48, 'subdistrict_tr' => 'MENTEŞE'],
            ['id' => 728, 'district_id' => 48, 'subdistrict_tr' => 'MİLAS'],
            ['id' => 729, 'district_id' => 48, 'subdistrict_tr' => 'ORTACA'],
            ['id' => 730, 'district_id' => 48, 'subdistrict_tr' => 'SEYDİKEMER'],
            ['id' => 731, 'district_id' => 48, 'subdistrict_tr' => 'ULA'],
            ['id' => 732, 'district_id' => 48, 'subdistrict_tr' => 'YATAĞAN'],
            //MUŞ
            ['id' => 733, 'district_id' => 49, 'subdistrict_tr' => 'BULANIK'],
            ['id' => 734, 'district_id' => 49, 'subdistrict_tr' => 'HASKÖY'],
            ['id' => 735, 'district_id' => 49, 'subdistrict_tr' => 'KORKUT'],
            ['id' => 736, 'district_id' => 49, 'subdistrict_tr' => 'MALAZGİRT'],
            ['id' => 737, 'district_id' => 49, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 738, 'district_id' => 49, 'subdistrict_tr' => 'VARTO'],
            //NEVŞEHİR
            ['id' => 739, 'district_id' => 50, 'subdistrict_tr' => 'ACIGÖL'],
            ['id' => 740, 'district_id' => 50, 'subdistrict_tr' => 'AVANOS'],
            ['id' => 741, 'district_id' => 50, 'subdistrict_tr' => 'DERİNKUYU'],
            ['id' => 742, 'district_id' => 50, 'subdistrict_tr' => 'GÜLŞEHİR'],
            ['id' => 743, 'district_id' => 50, 'subdistrict_tr' => 'HACIBEKTAŞ'],
            ['id' => 744, 'district_id' => 50, 'subdistrict_tr' => 'KOZAKLI'],
            ['id' => 745, 'district_id' => 50, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 746, 'district_id' => 50, 'subdistrict_tr' => 'ÜRGÜP'],
            //NİĞDE
            ['id' => 747, 'district_id' => 51, 'subdistrict_tr' => 'ALTUNHİSAR'],
            ['id' => 748, 'district_id' => 51, 'subdistrict_tr' => 'BOR'],
            ['id' => 749, 'district_id' => 51, 'subdistrict_tr' => 'ÇAMARDI'],
            ['id' => 750, 'district_id' => 51, 'subdistrict_tr' => 'ÇİFTLİK'],
            ['id' => 751, 'district_id' => 51, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 752, 'district_id' => 51, 'subdistrict_tr' => 'ULUKIŞLA'],
            //ORDU
            ['id' => 753, 'district_id' => 52, 'subdistrict_tr' => 'AKKUŞ'],
            ['id' => 754, 'district_id' => 52, 'subdistrict_tr' => 'ALTINORDU'],
            ['id' => 755, 'district_id' => 52, 'subdistrict_tr' => 'AYBASTI'],
            ['id' => 756, 'district_id' => 52, 'subdistrict_tr' => 'ÇAMAŞ'],
            ['id' => 757, 'district_id' => 52, 'subdistrict_tr' => 'ÇATALPINAR'],
            ['id' => 758, 'district_id' => 52, 'subdistrict_tr' => 'ÇAYBAŞI'],
            ['id' => 759, 'district_id' => 52, 'subdistrict_tr' => 'FATSA'],
            ['id' => 760, 'district_id' => 52, 'subdistrict_tr' => 'GÖLKÖY'],
            ['id' => 761, 'district_id' => 52, 'subdistrict_tr' => 'GÜLYALI'],
            ['id' => 762, 'district_id' => 52, 'subdistrict_tr' => 'GÜRGENTEPE'],
            ['id' => 763, 'district_id' => 52, 'subdistrict_tr' => 'İKİZCE'],
            ['id' => 764, 'district_id' => 52, 'subdistrict_tr' => 'KABADÜZ'],
            ['id' => 765, 'district_id' => 52, 'subdistrict_tr' => 'KABATAŞ'],
            ['id' => 766, 'district_id' => 52, 'subdistrict_tr' => 'KORGAN'],
            ['id' => 767, 'district_id' => 52, 'subdistrict_tr' => 'KUMRU'],
            ['id' => 768, 'district_id' => 52, 'subdistrict_tr' => 'MESUDİYE'],
            ['id' => 769, 'district_id' => 52, 'subdistrict_tr' => 'PERŞEMBE'],
            ['id' => 770, 'district_id' => 52, 'subdistrict_tr' => 'ULUBEY'],
            ['id' => 771, 'district_id' => 52, 'subdistrict_tr' => 'ÜNYE'],
            //oSMANİYE
            ['id' => 772, 'district_id' => 80, 'subdistrict_tr' => 'BAHÇE'],
            ['id' => 773, 'district_id' => 80, 'subdistrict_tr' => 'DÜZİÇİ'],
            ['id' => 774, 'district_id' => 80, 'subdistrict_tr' => 'HASANBEYLİ'],
            ['id' => 775, 'district_id' => 80, 'subdistrict_tr' => 'KADİRLİ'],
            ['id' => 776, 'district_id' => 80, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 777, 'district_id' => 80, 'subdistrict_tr' => 'SUMBAS'],
            ['id' => 778, 'district_id' => 80, 'subdistrict_tr' => 'TOPRAKKALE'],
            //RİZE
            ['id' => 779, 'district_id' => 53, 'subdistrict_tr' => 'ARDEŞEN'],
            ['id' => 780, 'district_id' => 53, 'subdistrict_tr' => 'ÇAMLIHEMŞİN'],
            ['id' => 781, 'district_id' => 53, 'subdistrict_tr' => 'ÇAYELİ'],
            ['id' => 782, 'district_id' => 53, 'subdistrict_tr' => 'DEREPAZARI'],
            ['id' => 783, 'district_id' => 53, 'subdistrict_tr' => 'FINDIKLI'],
            ['id' => 784, 'district_id' => 53, 'subdistrict_tr' => 'GÜNEYSU'],
            ['id' => 785, 'district_id' => 53, 'subdistrict_tr' => 'HEMŞİN'],
            ['id' => 786, 'district_id' => 53, 'subdistrict_tr' => 'İKİZDERE'],
            ['id' => 787, 'district_id' => 53, 'subdistrict_tr' => 'İYİDERE'],
            ['id' => 788, 'district_id' => 53, 'subdistrict_tr' => 'KALKANDERE'],
            ['id' => 789, 'district_id' => 53, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 790, 'district_id' => 53, 'subdistrict_tr' => 'PAZAR'],
            //SAKARYA
            ['id' => 791, 'district_id' => 54, 'subdistrict_tr' => 'ADAPAZARI'],
            ['id' => 792, 'district_id' => 54, 'subdistrict_tr' => 'AKYAZI'],
            ['id' => 793, 'district_id' => 54, 'subdistrict_tr' => 'ARİFİYE'],
            ['id' => 794, 'district_id' => 54, 'subdistrict_tr' => 'ERENLER'],
            ['id' => 795, 'district_id' => 54, 'subdistrict_tr' => 'FERİZLİ'],
            ['id' => 796, 'district_id' => 54, 'subdistrict_tr' => 'GEYVE'],
            ['id' => 797, 'district_id' => 54, 'subdistrict_tr' => 'HENDEK'],
            ['id' => 798, 'district_id' => 54, 'subdistrict_tr' => 'KARAPÜRÇEK'],
            ['id' => 799, 'district_id' => 54, 'subdistrict_tr' => 'KARASU'],
            ['id' => 800, 'district_id' => 54, 'subdistrict_tr' => 'KAYNARCA'],
            ['id' => 801, 'district_id' => 54, 'subdistrict_tr' => 'KOCAALİ'],
            ['id' => 802, 'district_id' => 54, 'subdistrict_tr' => 'PAMUKOVA'],
            ['id' => 803, 'district_id' => 54, 'subdistrict_tr' => 'SAPANCA'],
            ['id' => 804, 'district_id' => 54, 'subdistrict_tr' => 'SERDİVAN'],
            ['id' => 805, 'district_id' => 54, 'subdistrict_tr' => 'SÖĞÜTLÜ'],
            ['id' => 806, 'district_id' => 54, 'subdistrict_tr' => 'TARAKLI'],
            //SAMSUN
            ['id' => 807 ,'district_id' => 55, 'subdistrict_tr' => '19 MAYIS'],
            ['id' => 808, 'district_id' => 55, 'subdistrict_tr' => 'ALAÇAM'],
            ['id' => 809, 'district_id' => 55, 'subdistrict_tr' => 'ASARCIK'],
            ['id' => 810, 'district_id' => 55, 'subdistrict_tr' => 'ATAKUM'],
            ['id' => 811, 'district_id' => 55, 'subdistrict_tr' => 'AYVACIK'],
            ['id' => 812, 'district_id' => 55, 'subdistrict_tr' => 'BAFRA'],
            ['id' => 813, 'district_id' => 55, 'subdistrict_tr' => 'CANİK'],
            ['id' => 814, 'district_id' => 55, 'subdistrict_tr' => 'ÇARŞAMBA'],
            ['id' => 815, 'district_id' => 55, 'subdistrict_tr' => 'HAVZA'],
            ['id' => 816, 'district_id' => 55, 'subdistrict_tr' => 'İLKADIM'],
            ['id' => 817, 'district_id' => 55, 'subdistrict_tr' => 'KAVAK'],
            ['id' => 818, 'district_id' => 55, 'subdistrict_tr' => 'LADİK'],
            ['id' => 819, 'district_id' => 55, 'subdistrict_tr' => 'SALIPAZARI'],
            ['id' => 820, 'district_id' => 55, 'subdistrict_tr' => 'TEKKEKÖY'],
            ['id' => 821, 'district_id' => 55, 'subdistrict_tr' => 'TERME'],
            ['id' => 822, 'district_id' => 55, 'subdistrict_tr' => 'VEZİRKÖPRÜ'],
            ['id' => 823, 'district_id' => 55, 'subdistrict_tr' => 'YAKAKENT'],
            //SİİRT
            ['id' => 824, 'district_id' => 56, 'subdistrict_tr' => 'BAYKAN'],
            ['id' => 825, 'district_id' => 56, 'subdistrict_tr' => 'ERUH'],
            ['id' => 826, 'district_id' => 56, 'subdistrict_tr' => 'KURTALAN'],
            ['id' => 827, 'district_id' => 56, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 828, 'district_id' => 56, 'subdistrict_tr' => 'PERVARİ'],
            ['id' => 829, 'district_id' => 56, 'subdistrict_tr' => 'ŞİRVAN'],
            ['id' => 830, 'district_id' => 56, 'subdistrict_tr' => 'TİLLO'],
            //SİNOP
            ['id' => 831, 'district_id' => 57, 'subdistrict_tr' => 'AYANCIK'],
            ['id' => 832, 'district_id' => 57, 'subdistrict_tr' => 'BOYABAT'],
            ['id' => 833, 'district_id' => 57, 'subdistrict_tr' => 'DİKMEN'],
            ['id' => 834, 'district_id' => 57, 'subdistrict_tr' => 'DURAĞAN'],
            ['id' => 835, 'district_id' => 57, 'subdistrict_tr' => 'ERFELEK'],
            ['id' => 836, 'district_id' => 57, 'subdistrict_tr' => 'GERZE'],
            ['id' => 837, 'district_id' => 57, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 838, 'district_id' => 57, 'subdistrict_tr' => 'SARAYDÜZÜ'],
            ['id' => 839, 'district_id' => 57, 'subdistrict_tr' => 'TÜRKELİ'],
            //SİVAS
            ['id' => 840, 'district_id' => 58, 'subdistrict_tr' => 'AKINCILAR'],
            ['id' => 841, 'district_id' => 58, 'subdistrict_tr' => 'ALTINYAYLA'],
            ['id' => 842, 'district_id' => 58, 'subdistrict_tr' => 'DİVRİĞİ'],
            ['id' => 843, 'district_id' => 58, 'subdistrict_tr' => 'DOĞANŞAR'],
            ['id' => 844, 'district_id' => 58, 'subdistrict_tr' => 'GEMEREK'],
            ['id' => 845, 'district_id' => 58, 'subdistrict_tr' => 'GÖLOVA'],
            ['id' => 846, 'district_id' => 58, 'subdistrict_tr' => 'GÜRÜN'],
            ['id' => 847, 'district_id' => 58, 'subdistrict_tr' => 'HAFİK'],
            ['id' => 848, 'district_id' => 58, 'subdistrict_tr' => 'İMRANLI'],
            ['id' => 849, 'district_id' => 58, 'subdistrict_tr' => 'KANGAL'],
            ['id' => 850, 'district_id' => 58, 'subdistrict_tr' => 'KOYULHİSAR'],
            ['id' => 851, 'district_id' => 58, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 852, 'district_id' => 58, 'subdistrict_tr' => 'SUŞEHRİ'],
            ['id' => 853, 'district_id' => 58, 'subdistrict_tr' => 'ŞARKIŞLA'],
            ['id' => 854, 'district_id' => 58, 'subdistrict_tr' => 'ULAŞ'],
            ['id' => 855, 'district_id' => 58, 'subdistrict_tr' => 'YILDIZELİ'],
            ['id' => 856, 'district_id' => 58, 'subdistrict_tr' => 'ZARA'],
            //ŞANLIURFA
            ['id' => 857, 'district_id' => 63, 'subdistrict_tr' => 'AKÇAKALE'],
            ['id' => 858, 'district_id' => 63, 'subdistrict_tr' => 'BİRECİK'],
            ['id' => 859, 'district_id' => 63, 'subdistrict_tr' => 'BOZOVA'],
            ['id' => 860, 'district_id' => 63, 'subdistrict_tr' => 'CEYLANPINAR'],
            ['id' => 861, 'district_id' => 63, 'subdistrict_tr' => 'EYYÜBİYE'],
            ['id' => 862, 'district_id' => 63, 'subdistrict_tr' => 'HALFETİ'],
            ['id' => 863, 'district_id' => 63, 'subdistrict_tr' => 'HALİLİYE'],
            ['id' => 864, 'district_id' => 63, 'subdistrict_tr' => 'HARRAN'],
            ['id' => 865, 'district_id' => 63, 'subdistrict_tr' => 'HİLVAN'],
            ['id' => 866, 'district_id' => 63, 'subdistrict_tr' => 'KARAKÖPRÜ'],
            ['id' => 867, 'district_id' => 63, 'subdistrict_tr' => 'SİVEREK'],
            ['id' => 868, 'district_id' => 63, 'subdistrict_tr' => 'SURUÇ'],
            ['id' => 869, 'district_id' => 63, 'subdistrict_tr' => 'VİRANŞEHİR'],
            //ŞIRNAK
            ['id' => 870, 'district_id' => 73,'subdistrict_tr' => 'BEYTÜŞŞEBAP'],
            ['id' => 871, 'district_id' => 73,'subdistrict_tr' => 'CİZRE'],
            ['id' => 872, 'district_id' => 73,'subdistrict_tr' => 'GÜÇLÜKONAK'],
            ['id' => 873, 'district_id' => 73,'subdistrict_tr' => 'İDİL'],
            ['id' => 874, 'district_id' => 73,'subdistrict_tr' => 'MERKEZ'],
            ['id' => 875, 'district_id' => 73,'subdistrict_tr' => 'SİLOPİ'],
            ['id' => 876, 'district_id' => 73,'subdistrict_tr' => 'ULUDERE'],
            //TEKİRDAĞ
            ['id' => 877, 'district_id' => 59, 'subdistrict_tr' => 'ÇERKEZKÖY'],
            ['id' => 878, 'district_id' => 59, 'subdistrict_tr' => 'ÇORLU'],
            ['id' => 879, 'district_id' => 59, 'subdistrict_tr' => 'ERGENE'],
            ['id' => 880, 'district_id' => 59, 'subdistrict_tr' => 'HAYRABOLU'],
            ['id' => 881, 'district_id' => 59, 'subdistrict_tr' => 'KAPAKLI'],
            ['id' => 882, 'district_id' => 59, 'subdistrict_tr' => 'MALKARA'],
            ['id' => 883, 'district_id' => 59, 'subdistrict_tr' => 'MARMARAEREĞLİSİ'],
            ['id' => 884, 'district_id' => 59, 'subdistrict_tr' => 'MURATLI'],
            ['id' => 885, 'district_id' => 59, 'subdistrict_tr' => 'SARAY'],
            ['id' => 886, 'district_id' => 59, 'subdistrict_tr' => 'SÜLEYMANPAŞA'],
            ['id' => 887, 'district_id' => 59, 'subdistrict_tr' => 'ŞARKÖY'],
            //TOKAT
            ['id' => 888, 'district_id' => 60,'subdistrict_tr' => 'ALMUS'],
            ['id' => 889, 'district_id' => 60,'subdistrict_tr' => 'ARTOVA'],
            ['id' => 890, 'district_id' => 60,'subdistrict_tr' => 'BAŞÇİFTLİK'],
            ['id' => 891, 'district_id' => 60,'subdistrict_tr' => 'ERBAA'],
            ['id' => 892, 'district_id' => 60,'subdistrict_tr' => 'MERKEZ'],
            ['id' => 893, 'district_id' => 60,'subdistrict_tr' => 'NİKSAR'],
            ['id' => 894, 'district_id' => 60,'subdistrict_tr' => 'PAZAR'],
            ['id' => 895, 'district_id' => 60,'subdistrict_tr' => 'REŞADİYE'],
            ['id' => 896, 'district_id' => 60,'subdistrict_tr' => 'SULUSARAY'],
            ['id' => 897, 'district_id' => 60,'subdistrict_tr' => 'TURHAL'],
            ['id' => 898, 'district_id' => 60,'subdistrict_tr' => 'YEŞİLYURT'],
            ['id' => 899, 'district_id' => 60,'subdistrict_tr' => 'ZİLE'],
            //TRABZON
            ['id' => 900, 'district_id' => 61, 'subdistrict_tr' => 'AKÇAABAT'],
            ['id' => 901, 'district_id' => 61, 'subdistrict_tr' => 'ARAKLI'],
            ['id' => 902, 'district_id' => 61, 'subdistrict_tr' => 'ARSİN'],
            ['id' => 903, 'district_id' => 61, 'subdistrict_tr' => 'BEŞİKDÜZÜ'],
            ['id' => 904, 'district_id' => 61, 'subdistrict_tr' => 'ÇARŞIBAŞI'],
            ['id' => 905, 'district_id' => 61, 'subdistrict_tr' => 'ÇAYKARA'],
            ['id' => 906, 'district_id' => 61, 'subdistrict_tr' => 'DERNEKPAZARI'],
            ['id' => 907, 'district_id' => 61, 'subdistrict_tr' => 'DÜZKÖY'],
            ['id' => 908, 'district_id' => 61, 'subdistrict_tr' => 'HAYRAT'],
            ['id' => 909, 'district_id' => 61, 'subdistrict_tr' => 'KÖPRÜBAŞI'],
            ['id' => 910, 'district_id' => 61, 'subdistrict_tr' => 'MAÇKA'],
            ['id' => 911, 'district_id' => 61, 'subdistrict_tr' => 'OF'],
            ['id' => 912, 'district_id' => 61, 'subdistrict_tr' => 'ORTAHİSAR'],
            ['id' => 913, 'district_id' => 61, 'subdistrict_tr' => 'SÜRMENE'],
            ['id' => 914, 'district_id' => 61, 'subdistrict_tr' => 'ŞALPAZARI'],
            ['id' => 915, 'district_id' => 61, 'subdistrict_tr' => 'TONYA'],
            ['id' => 916, 'district_id' => 61, 'subdistrict_tr' => 'VAKFIKEBİR'],
            ['id' => 917, 'district_id' => 61, 'subdistrict_tr' => 'YOMRA'],
            //TUNCELİ
            ['id' => 918, 'district_id' => 62, 'subdistrict_tr' => 'ÇEMİŞGEZEK'],
            ['id' => 919, 'district_id' => 62, 'subdistrict_tr' => 'HOZAT'],
            ['id' => 920, 'district_id' => 62, 'subdistrict_tr' => 'MAZGİRT'],
            ['id' => 921, 'district_id' => 62, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 922, 'district_id' => 62, 'subdistrict_tr' => 'NAZIMİYE'],
            ['id' => 923, 'district_id' => 62, 'subdistrict_tr' => 'OVACIK'],
            ['id' => 924, 'district_id' => 62, 'subdistrict_tr' => 'PERTEK'],
            ['id' => 925, 'district_id' => 62, 'subdistrict_tr' => 'PÜLÜMÜR'],
            //UŞAK
            ['id' => 926, 'district_id' => 64, 'subdistrict_tr' => 'BANAZ'],
            ['id' => 927, 'district_id' => 64, 'subdistrict_tr' => 'EŞME'],
            ['id' => 928, 'district_id' => 64, 'subdistrict_tr' => 'KARAHALLI'],
            ['id' => 929, 'district_id' => 64, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 930, 'district_id' => 64, 'subdistrict_tr' => 'SİVASLI'],
            ['id' => 931, 'district_id' => 64, 'subdistrict_tr' => 'ULUBEY'],
            //VAN
            ['id' => 932, 'district_id' => 65, 'subdistrict_tr' => 'BAHÇESARAY'],
            ['id' => 933, 'district_id' => 65, 'subdistrict_tr' => 'BAŞKALE'],
            ['id' => 934, 'district_id' => 65, 'subdistrict_tr' => 'ÇALDIRAN'],
            ['id' => 935, 'district_id' => 65, 'subdistrict_tr' => 'ÇATAK'],
            ['id' => 936, 'district_id' => 65, 'subdistrict_tr' => 'EDREMİT'],
            ['id' => 937, 'district_id' => 65, 'subdistrict_tr' => 'ERCİŞ'],
            ['id' => 938, 'district_id' => 65, 'subdistrict_tr' => 'GEVAŞ'],
            ['id' => 939, 'district_id' => 65, 'subdistrict_tr' => 'GÜRPINAR'],
            ['id' => 940, 'district_id' => 65, 'subdistrict_tr' => 'İPEKYOLU'],
            ['id' => 941, 'district_id' => 65, 'subdistrict_tr' => 'MURADİYE'],
            ['id' => 942, 'district_id' => 65, 'subdistrict_tr' => 'ÖZALP'],
            ['id' => 943, 'district_id' => 65, 'subdistrict_tr' => 'SARAY'],
            ['id' => 944, 'district_id' => 65, 'subdistrict_tr' => 'TUŞBA'],
            //YALOVA
            ['id' => 945, 'district_id' => 77, 'subdistrict_tr' => 'ALTINOVA'],
            ['id' => 946, 'district_id' => 77, 'subdistrict_tr' => 'ARMUTLU'],
            ['id' => 947, 'district_id' => 77, 'subdistrict_tr' => 'ÇINARCIK'],
            ['id' => 948, 'district_id' => 77, 'subdistrict_tr' => 'ÇİFTLİKKÖY'],
            ['id' => 949, 'district_id' => 77, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 950, 'district_id' => 77, 'subdistrict_tr' => 'TERMAL'],
            //YOZGAT
            ['id' => 951, 'district_id' => 66, 'subdistrict_tr' => 'AKDAĞMADENİ'],
            ['id' => 952, 'district_id' => 66, 'subdistrict_tr' => 'AYDINCIK'],
            ['id' => 953, 'district_id' => 66, 'subdistrict_tr' => 'BOĞAZLIYAN'],
            ['id' => 954, 'district_id' => 66, 'subdistrict_tr' => 'ÇANDIR'],
            ['id' => 955, 'district_id' => 66, 'subdistrict_tr' => 'ÇAYIRALAN'],
            ['id' => 956, 'district_id' => 66, 'subdistrict_tr' => 'ÇEKEREK'],
            ['id' => 957, 'district_id' => 66, 'subdistrict_tr' => 'KADIŞEHRİ'],
            ['id' => 958, 'district_id' => 66, 'subdistrict_tr' => 'MERKEZ'],
            ['id' => 959, 'district_id' => 66, 'subdistrict_tr' => 'SARAYKENT'],
            ['id' => 960, 'district_id' => 66, 'subdistrict_tr' => 'SARIKAYA'],
            ['id' => 961, 'district_id' => 66, 'subdistrict_tr' => 'SORGUN'],
            ['id' => 962, 'district_id' => 66, 'subdistrict_tr' => 'ŞEFAATLİ'],
            ['id' => 963, 'district_id' => 66, 'subdistrict_tr' => 'YENİFAKILI'],
            ['id' => 964, 'district_id' => 66, 'subdistrict_tr' => 'YERKÖY'],
            //ZONGULDAK
            ['id' => 965, 'district_id' => 67, 'subdistrict_tr' => 'ALAPLI'],
            ['id' => 966, 'district_id' => 67, 'subdistrict_tr' => 'ÇAYCUMA'],
            ['id' => 967, 'district_id' => 67, 'subdistrict_tr' => 'DEVREK'],
            ['id' => 968, 'district_id' => 67, 'subdistrict_tr' => 'EREĞLİ'],
            ['id' => 969, 'district_id' => 67, 'subdistrict_tr' => 'GÖKÇEBEY'],
            ['id' => 970, 'district_id' => 67, 'subdistrict_tr' => 'KİLİMLİ'],
            ['id' => 971, 'district_id' => 67, 'subdistrict_tr' => 'KOZLU'],
            ['id' => 972, 'district_id' => 67, 'subdistrict_tr' => 'MERKEZ']
        ]);
    }
}
